### ISSUE TITLE
Subjects for XProc standards update talk?

### ISSUE THREAD

**Issue by xatapult** [xproc/Workshop-2-2019#3]
I've volunteered to do the standards update talk on the conference. I would value your opinions on which advancements *must* be mentioned there. Just a quick poll. 

Of course, given the limited amount of time, not sure I can squeeze everything in, but I also don't want to miss anything important.

Here are the obvious candidates:

- Upgrade to XPath 3.1 and XDM
- Documents have a property map attached
- Support for HTML, JSON, Text and binary documents
- Introduction of AVTs and TVTs
- Static variables/options and their usage
- Usage of maps (for parameter passing, serialization, etc.)
- `p:input` ==> `p:with-input`
- Syntactic sugary stuff:
  -  `@pipe`, `@href`, ...
  - Option to leave out  `p:inline`
  
Anything about the step library?

**Comment by mgaerber** [comment]
Will this be at the pre or main conf?

**Comment by xatapult** [comment]
Main, but its still a submission, so not 100% sure we're on.

**Comment by xml-project** [comment]
>Will this be at the pre or main conf?

But we also filed a proposal for a slot on unconference day to talk on XProc 3.0.

**Comment by mgaerber** [comment]
For the main conf I think maximum sugar is needed ;-)

But jokes aside, at our company we looked multiple times into xproc but gave up because of 
* no text/binary documents processing
* missing steps (ftp, md5, zip ...)
* hard to understand pipe definition syntax

And as time passed by, one person created something very similar to xproc: 
https://github.com/axxepta/converterservices/wiki/Command-line-Pipeline

This could have been done with xproc...

**Comment by xatapult** [comment]
@mgaerber Well, I hope the new definition is more to your liking then. About missing steps: This is still open. We're going to talk about this at the pre-conference XProc workshop in Prague (Tuesday and Wednesday). 

If you cant attend please send in your ideas and wishlist!

**Comment by xml-project** [comment]
@eriksiegel can we close this?

**Comment by xatapult** [comment]
Yep
